name: Auto Deploy - EHB Home Page

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node.js dependencies
      run: npm install

    - name: Run tests
      run: |
        python quick_test.py
        python test_integrations.py

    - name: Build frontend
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out

    - name: Create deployment summary
      run: |
        echo "# 🚀 Auto Deployment Summary" > deployment_summary.md
        echo "**Date:** $(date)" >> deployment_summary.md
        echo "**Branch:** ${{ github.ref }}" >> deployment_summary.md
        echo "**Commit:** ${{ github.sha }}" >> deployment_summary.md
        echo "" >> deployment_summary.md
        echo "## ✅ Deployment Status" >> deployment_summary.md
        echo "- Tests: ✅ Passed" >> deployment_summary.md
        echo "- Build: ✅ Successful" >> deployment_summary.md
        echo "- Deployment: ✅ Completed" >> deployment_summary.md

    - name: Upload deployment summary
      uses: actions/upload-artifact@v3
      with:
        name: deployment-summary
        path: deployment_summary.md

  notify-deployment:
    needs: test-and-deploy
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.test-and-deploy.result }}" == "success" ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
